/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSecurityIndexRouteImport } from './routes/dashboard.security.index'
import { Route as DashboardResidentIndexRouteImport } from './routes/dashboard.resident.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardSecurityVisitorLogsRouteImport } from './routes/dashboard.security.visitor-logs'
import { Route as DashboardSecurityAddVisitorRouteImport } from './routes/dashboard.security.add-visitor'
import { Route as DashboardSecurityActiveVisitorsRouteImport } from './routes/dashboard.security.active-visitors'
import { Route as DashboardResidentSettingsRouteImport } from './routes/dashboard.resident.settings'
import { Route as DashboardResidentProfileRouteImport } from './routes/dashboard.resident.profile'
import { Route as DashboardResidentParkingRouteImport } from './routes/dashboard.resident.parking'
import { Route as DashboardResidentNoticesRouteImport } from './routes/dashboard.resident.notices'
import { Route as DashboardResidentFlatRouteImport } from './routes/dashboard.resident.flat'
import { Route as DashboardResidentComplaintsRouteImport } from './routes/dashboard.resident.complaints'
import { Route as DashboardResidentBillingRouteImport } from './routes/dashboard.resident.billing'
import { Route as DashboardAdminVisitorsRouteImport } from './routes/dashboard.admin.visitors'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminResidentsRouteImport } from './routes/dashboard.admin.residents'
import { Route as DashboardAdminParkingRouteImport } from './routes/dashboard.admin.parking'
import { Route as DashboardAdminNoticesRouteImport } from './routes/dashboard.admin.notices'
import { Route as DashboardAdminMaintenanceRouteImport } from './routes/dashboard.admin.maintenance'
import { Route as DashboardAdminFlatsRouteImport } from './routes/dashboard.admin.flats'
import { Route as DashboardAdminComplaintsRouteImport } from './routes/dashboard.admin.complaints'
import { Route as DashboardAdminBillingRouteImport } from './routes/dashboard.admin.billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityIndexRoute = DashboardSecurityIndexRouteImport.update({
  id: '/dashboard/security/',
  path: '/dashboard/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResidentIndexRoute = DashboardResidentIndexRouteImport.update({
  id: '/dashboard/resident/',
  path: '/dashboard/resident/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityVisitorLogsRoute =
  DashboardSecurityVisitorLogsRouteImport.update({
    id: '/dashboard/security/visitor-logs',
    path: '/dashboard/security/visitor-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSecurityAddVisitorRoute =
  DashboardSecurityAddVisitorRouteImport.update({
    id: '/dashboard/security/add-visitor',
    path: '/dashboard/security/add-visitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSecurityActiveVisitorsRoute =
  DashboardSecurityActiveVisitorsRouteImport.update({
    id: '/dashboard/security/active-visitors',
    path: '/dashboard/security/active-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentSettingsRoute =
  DashboardResidentSettingsRouteImport.update({
    id: '/dashboard/resident/settings',
    path: '/dashboard/resident/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentProfileRoute =
  DashboardResidentProfileRouteImport.update({
    id: '/dashboard/resident/profile',
    path: '/dashboard/resident/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentParkingRoute =
  DashboardResidentParkingRouteImport.update({
    id: '/dashboard/resident/parking',
    path: '/dashboard/resident/parking',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentNoticesRoute =
  DashboardResidentNoticesRouteImport.update({
    id: '/dashboard/resident/notices',
    path: '/dashboard/resident/notices',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentFlatRoute = DashboardResidentFlatRouteImport.update({
  id: '/dashboard/resident/flat',
  path: '/dashboard/resident/flat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResidentComplaintsRoute =
  DashboardResidentComplaintsRouteImport.update({
    id: '/dashboard/resident/complaints',
    path: '/dashboard/resident/complaints',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardResidentBillingRoute =
  DashboardResidentBillingRouteImport.update({
    id: '/dashboard/resident/billing',
    path: '/dashboard/resident/billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminVisitorsRoute = DashboardAdminVisitorsRouteImport.update({
  id: '/dashboard/admin/visitors',
  path: '/dashboard/admin/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/dashboard/admin/settings',
  path: '/dashboard/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminResidentsRoute = DashboardAdminResidentsRouteImport.update({
  id: '/dashboard/admin/residents',
  path: '/dashboard/admin/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminParkingRoute = DashboardAdminParkingRouteImport.update({
  id: '/dashboard/admin/parking',
  path: '/dashboard/admin/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminNoticesRoute = DashboardAdminNoticesRouteImport.update({
  id: '/dashboard/admin/notices',
  path: '/dashboard/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminMaintenanceRoute =
  DashboardAdminMaintenanceRouteImport.update({
    id: '/dashboard/admin/maintenance',
    path: '/dashboard/admin/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminFlatsRoute = DashboardAdminFlatsRouteImport.update({
  id: '/dashboard/admin/flats',
  path: '/dashboard/admin/flats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminComplaintsRoute =
  DashboardAdminComplaintsRouteImport.update({
    id: '/dashboard/admin/complaints',
    path: '/dashboard/admin/complaints',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminBillingRoute = DashboardAdminBillingRouteImport.update({
  id: '/dashboard/admin/billing',
  path: '/dashboard/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/resident/': typeof DashboardResidentIndexRoute
  '/dashboard/security/': typeof DashboardSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/resident': typeof DashboardResidentIndexRoute
  '/dashboard/security': typeof DashboardSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/resident/': typeof DashboardResidentIndexRoute
  '/dashboard/security/': typeof DashboardSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
    | '/dashboard/admin/'
    | '/dashboard/resident/'
    | '/dashboard/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
    | '/dashboard/admin/'
    | '/dashboard/resident/'
    | '/dashboard/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardAdminBillingRoute: typeof DashboardAdminBillingRoute
  DashboardAdminComplaintsRoute: typeof DashboardAdminComplaintsRoute
  DashboardAdminFlatsRoute: typeof DashboardAdminFlatsRoute
  DashboardAdminMaintenanceRoute: typeof DashboardAdminMaintenanceRoute
  DashboardAdminNoticesRoute: typeof DashboardAdminNoticesRoute
  DashboardAdminParkingRoute: typeof DashboardAdminParkingRoute
  DashboardAdminResidentsRoute: typeof DashboardAdminResidentsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminVisitorsRoute: typeof DashboardAdminVisitorsRoute
  DashboardResidentBillingRoute: typeof DashboardResidentBillingRoute
  DashboardResidentComplaintsRoute: typeof DashboardResidentComplaintsRoute
  DashboardResidentFlatRoute: typeof DashboardResidentFlatRoute
  DashboardResidentNoticesRoute: typeof DashboardResidentNoticesRoute
  DashboardResidentParkingRoute: typeof DashboardResidentParkingRoute
  DashboardResidentProfileRoute: typeof DashboardResidentProfileRoute
  DashboardResidentSettingsRoute: typeof DashboardResidentSettingsRoute
  DashboardSecurityActiveVisitorsRoute: typeof DashboardSecurityActiveVisitorsRoute
  DashboardSecurityAddVisitorRoute: typeof DashboardSecurityAddVisitorRoute
  DashboardSecurityVisitorLogsRoute: typeof DashboardSecurityVisitorLogsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardResidentIndexRoute: typeof DashboardResidentIndexRoute
  DashboardSecurityIndexRoute: typeof DashboardSecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security/': {
      id: '/dashboard/security/'
      path: '/dashboard/security'
      fullPath: '/dashboard/security/'
      preLoaderRoute: typeof DashboardSecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/': {
      id: '/dashboard/resident/'
      path: '/dashboard/resident'
      fullPath: '/dashboard/resident/'
      preLoaderRoute: typeof DashboardResidentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security/visitor-logs': {
      id: '/dashboard/security/visitor-logs'
      path: '/dashboard/security/visitor-logs'
      fullPath: '/dashboard/security/visitor-logs'
      preLoaderRoute: typeof DashboardSecurityVisitorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security/add-visitor': {
      id: '/dashboard/security/add-visitor'
      path: '/dashboard/security/add-visitor'
      fullPath: '/dashboard/security/add-visitor'
      preLoaderRoute: typeof DashboardSecurityAddVisitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security/active-visitors': {
      id: '/dashboard/security/active-visitors'
      path: '/dashboard/security/active-visitors'
      fullPath: '/dashboard/security/active-visitors'
      preLoaderRoute: typeof DashboardSecurityActiveVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/settings': {
      id: '/dashboard/resident/settings'
      path: '/dashboard/resident/settings'
      fullPath: '/dashboard/resident/settings'
      preLoaderRoute: typeof DashboardResidentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/profile': {
      id: '/dashboard/resident/profile'
      path: '/dashboard/resident/profile'
      fullPath: '/dashboard/resident/profile'
      preLoaderRoute: typeof DashboardResidentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/parking': {
      id: '/dashboard/resident/parking'
      path: '/dashboard/resident/parking'
      fullPath: '/dashboard/resident/parking'
      preLoaderRoute: typeof DashboardResidentParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/notices': {
      id: '/dashboard/resident/notices'
      path: '/dashboard/resident/notices'
      fullPath: '/dashboard/resident/notices'
      preLoaderRoute: typeof DashboardResidentNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/flat': {
      id: '/dashboard/resident/flat'
      path: '/dashboard/resident/flat'
      fullPath: '/dashboard/resident/flat'
      preLoaderRoute: typeof DashboardResidentFlatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/complaints': {
      id: '/dashboard/resident/complaints'
      path: '/dashboard/resident/complaints'
      fullPath: '/dashboard/resident/complaints'
      preLoaderRoute: typeof DashboardResidentComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident/billing': {
      id: '/dashboard/resident/billing'
      path: '/dashboard/resident/billing'
      fullPath: '/dashboard/resident/billing'
      preLoaderRoute: typeof DashboardResidentBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/visitors': {
      id: '/dashboard/admin/visitors'
      path: '/dashboard/admin/visitors'
      fullPath: '/dashboard/admin/visitors'
      preLoaderRoute: typeof DashboardAdminVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/dashboard/admin/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/residents': {
      id: '/dashboard/admin/residents'
      path: '/dashboard/admin/residents'
      fullPath: '/dashboard/admin/residents'
      preLoaderRoute: typeof DashboardAdminResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/parking': {
      id: '/dashboard/admin/parking'
      path: '/dashboard/admin/parking'
      fullPath: '/dashboard/admin/parking'
      preLoaderRoute: typeof DashboardAdminParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/notices': {
      id: '/dashboard/admin/notices'
      path: '/dashboard/admin/notices'
      fullPath: '/dashboard/admin/notices'
      preLoaderRoute: typeof DashboardAdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/maintenance': {
      id: '/dashboard/admin/maintenance'
      path: '/dashboard/admin/maintenance'
      fullPath: '/dashboard/admin/maintenance'
      preLoaderRoute: typeof DashboardAdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/flats': {
      id: '/dashboard/admin/flats'
      path: '/dashboard/admin/flats'
      fullPath: '/dashboard/admin/flats'
      preLoaderRoute: typeof DashboardAdminFlatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/complaints': {
      id: '/dashboard/admin/complaints'
      path: '/dashboard/admin/complaints'
      fullPath: '/dashboard/admin/complaints'
      preLoaderRoute: typeof DashboardAdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/billing': {
      id: '/dashboard/admin/billing'
      path: '/dashboard/admin/billing'
      fullPath: '/dashboard/admin/billing'
      preLoaderRoute: typeof DashboardAdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardAdminBillingRoute: DashboardAdminBillingRoute,
  DashboardAdminComplaintsRoute: DashboardAdminComplaintsRoute,
  DashboardAdminFlatsRoute: DashboardAdminFlatsRoute,
  DashboardAdminMaintenanceRoute: DashboardAdminMaintenanceRoute,
  DashboardAdminNoticesRoute: DashboardAdminNoticesRoute,
  DashboardAdminParkingRoute: DashboardAdminParkingRoute,
  DashboardAdminResidentsRoute: DashboardAdminResidentsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminVisitorsRoute: DashboardAdminVisitorsRoute,
  DashboardResidentBillingRoute: DashboardResidentBillingRoute,
  DashboardResidentComplaintsRoute: DashboardResidentComplaintsRoute,
  DashboardResidentFlatRoute: DashboardResidentFlatRoute,
  DashboardResidentNoticesRoute: DashboardResidentNoticesRoute,
  DashboardResidentParkingRoute: DashboardResidentParkingRoute,
  DashboardResidentProfileRoute: DashboardResidentProfileRoute,
  DashboardResidentSettingsRoute: DashboardResidentSettingsRoute,
  DashboardSecurityActiveVisitorsRoute: DashboardSecurityActiveVisitorsRoute,
  DashboardSecurityAddVisitorRoute: DashboardSecurityAddVisitorRoute,
  DashboardSecurityVisitorLogsRoute: DashboardSecurityVisitorLogsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardResidentIndexRoute: DashboardResidentIndexRoute,
  DashboardSecurityIndexRoute: DashboardSecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
