/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardResidentRouteImport } from './routes/dashboard.resident'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAdminVisitorsRouteImport } from './routes/dashboard.admin.visitors'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminResidentsRouteImport } from './routes/dashboard.admin.residents'
import { Route as DashboardAdminParkingRouteImport } from './routes/dashboard.admin.parking'
import { Route as DashboardAdminNoticesRouteImport } from './routes/dashboard.admin.notices'
import { Route as DashboardAdminMaintenanceRouteImport } from './routes/dashboard.admin.maintenance'
import { Route as DashboardAdminFlatsRouteImport } from './routes/dashboard.admin.flats'
import { Route as DashboardAdminComplaintsRouteImport } from './routes/dashboard.admin.complaints'
import { Route as DashboardAdminBillingRouteImport } from './routes/dashboard.admin.billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResidentRoute = DashboardResidentRouteImport.update({
  id: '/dashboard/resident',
  path: '/dashboard/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminVisitorsRoute = DashboardAdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminResidentsRoute = DashboardAdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminParkingRoute = DashboardAdminParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminNoticesRoute = DashboardAdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminMaintenanceRoute =
  DashboardAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminFlatsRoute = DashboardAdminFlatsRouteImport.update({
  id: '/flats',
  path: '/flats',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminComplaintsRoute =
  DashboardAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminBillingRoute = DashboardAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardResidentRoute: typeof DashboardResidentRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident': {
      id: '/dashboard/resident'
      path: '/dashboard/resident'
      fullPath: '/dashboard/resident'
      preLoaderRoute: typeof DashboardResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/visitors': {
      id: '/dashboard/admin/visitors'
      path: '/visitors'
      fullPath: '/dashboard/admin/visitors'
      preLoaderRoute: typeof DashboardAdminVisitorsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/residents': {
      id: '/dashboard/admin/residents'
      path: '/residents'
      fullPath: '/dashboard/admin/residents'
      preLoaderRoute: typeof DashboardAdminResidentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/parking': {
      id: '/dashboard/admin/parking'
      path: '/parking'
      fullPath: '/dashboard/admin/parking'
      preLoaderRoute: typeof DashboardAdminParkingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/notices': {
      id: '/dashboard/admin/notices'
      path: '/notices'
      fullPath: '/dashboard/admin/notices'
      preLoaderRoute: typeof DashboardAdminNoticesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/maintenance': {
      id: '/dashboard/admin/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/admin/maintenance'
      preLoaderRoute: typeof DashboardAdminMaintenanceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/flats': {
      id: '/dashboard/admin/flats'
      path: '/flats'
      fullPath: '/dashboard/admin/flats'
      preLoaderRoute: typeof DashboardAdminFlatsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/complaints': {
      id: '/dashboard/admin/complaints'
      path: '/complaints'
      fullPath: '/dashboard/admin/complaints'
      preLoaderRoute: typeof DashboardAdminComplaintsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/billing': {
      id: '/dashboard/admin/billing'
      path: '/billing'
      fullPath: '/dashboard/admin/billing'
      preLoaderRoute: typeof DashboardAdminBillingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBillingRoute: typeof DashboardAdminBillingRoute
  DashboardAdminComplaintsRoute: typeof DashboardAdminComplaintsRoute
  DashboardAdminFlatsRoute: typeof DashboardAdminFlatsRoute
  DashboardAdminMaintenanceRoute: typeof DashboardAdminMaintenanceRoute
  DashboardAdminNoticesRoute: typeof DashboardAdminNoticesRoute
  DashboardAdminParkingRoute: typeof DashboardAdminParkingRoute
  DashboardAdminResidentsRoute: typeof DashboardAdminResidentsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminVisitorsRoute: typeof DashboardAdminVisitorsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBillingRoute: DashboardAdminBillingRoute,
  DashboardAdminComplaintsRoute: DashboardAdminComplaintsRoute,
  DashboardAdminFlatsRoute: DashboardAdminFlatsRoute,
  DashboardAdminMaintenanceRoute: DashboardAdminMaintenanceRoute,
  DashboardAdminNoticesRoute: DashboardAdminNoticesRoute,
  DashboardAdminParkingRoute: DashboardAdminParkingRoute,
  DashboardAdminResidentsRoute: DashboardAdminResidentsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminVisitorsRoute: DashboardAdminVisitorsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardResidentRoute: DashboardResidentRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
