/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardResidentRouteImport } from './routes/dashboard.resident'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardSecurityVisitorLogsRouteImport } from './routes/dashboard.security.visitor-logs'
import { Route as DashboardSecurityAddVisitorRouteImport } from './routes/dashboard.security.add-visitor'
import { Route as DashboardSecurityActiveVisitorsRouteImport } from './routes/dashboard.security.active-visitors'
import { Route as DashboardResidentSettingsRouteImport } from './routes/dashboard.resident.settings'
import { Route as DashboardResidentProfileRouteImport } from './routes/dashboard.resident.profile'
import { Route as DashboardResidentParkingRouteImport } from './routes/dashboard.resident.parking'
import { Route as DashboardResidentNoticesRouteImport } from './routes/dashboard.resident.notices'
import { Route as DashboardResidentFlatRouteImport } from './routes/dashboard.resident.flat'
import { Route as DashboardResidentComplaintsRouteImport } from './routes/dashboard.resident.complaints'
import { Route as DashboardResidentBillingRouteImport } from './routes/dashboard.resident.billing'
import { Route as DashboardAdminVisitorsRouteImport } from './routes/dashboard.admin.visitors'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminResidentsRouteImport } from './routes/dashboard.admin.residents'
import { Route as DashboardAdminParkingRouteImport } from './routes/dashboard.admin.parking'
import { Route as DashboardAdminNoticesRouteImport } from './routes/dashboard.admin.notices'
import { Route as DashboardAdminMaintenanceRouteImport } from './routes/dashboard.admin.maintenance'
import { Route as DashboardAdminFlatsRouteImport } from './routes/dashboard.admin.flats'
import { Route as DashboardAdminComplaintsRouteImport } from './routes/dashboard.admin.complaints'
import { Route as DashboardAdminBillingRouteImport } from './routes/dashboard.admin.billing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResidentRoute = DashboardResidentRouteImport.update({
  id: '/dashboard/resident',
  path: '/dashboard/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityVisitorLogsRoute =
  DashboardSecurityVisitorLogsRouteImport.update({
    id: '/visitor-logs',
    path: '/visitor-logs',
    getParentRoute: () => DashboardSecurityRoute,
  } as any)
const DashboardSecurityAddVisitorRoute =
  DashboardSecurityAddVisitorRouteImport.update({
    id: '/add-visitor',
    path: '/add-visitor',
    getParentRoute: () => DashboardSecurityRoute,
  } as any)
const DashboardSecurityActiveVisitorsRoute =
  DashboardSecurityActiveVisitorsRouteImport.update({
    id: '/active-visitors',
    path: '/active-visitors',
    getParentRoute: () => DashboardSecurityRoute,
  } as any)
const DashboardResidentSettingsRoute =
  DashboardResidentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardResidentProfileRoute =
  DashboardResidentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardResidentParkingRoute =
  DashboardResidentParkingRouteImport.update({
    id: '/parking',
    path: '/parking',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardResidentNoticesRoute =
  DashboardResidentNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardResidentFlatRoute = DashboardResidentFlatRouteImport.update({
  id: '/flat',
  path: '/flat',
  getParentRoute: () => DashboardResidentRoute,
} as any)
const DashboardResidentComplaintsRoute =
  DashboardResidentComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardResidentBillingRoute =
  DashboardResidentBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => DashboardResidentRoute,
  } as any)
const DashboardAdminVisitorsRoute = DashboardAdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminResidentsRoute = DashboardAdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminParkingRoute = DashboardAdminParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminNoticesRoute = DashboardAdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminMaintenanceRoute =
  DashboardAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminFlatsRoute = DashboardAdminFlatsRouteImport.update({
  id: '/flats',
  path: '/flats',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminComplaintsRoute =
  DashboardAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminBillingRoute = DashboardAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRouteWithChildren
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRouteWithChildren
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/resident': typeof DashboardResidentRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRouteWithChildren
  '/dashboard/admin/billing': typeof DashboardAdminBillingRoute
  '/dashboard/admin/complaints': typeof DashboardAdminComplaintsRoute
  '/dashboard/admin/flats': typeof DashboardAdminFlatsRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/admin/notices': typeof DashboardAdminNoticesRoute
  '/dashboard/admin/parking': typeof DashboardAdminParkingRoute
  '/dashboard/admin/residents': typeof DashboardAdminResidentsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/visitors': typeof DashboardAdminVisitorsRoute
  '/dashboard/resident/billing': typeof DashboardResidentBillingRoute
  '/dashboard/resident/complaints': typeof DashboardResidentComplaintsRoute
  '/dashboard/resident/flat': typeof DashboardResidentFlatRoute
  '/dashboard/resident/notices': typeof DashboardResidentNoticesRoute
  '/dashboard/resident/parking': typeof DashboardResidentParkingRoute
  '/dashboard/resident/profile': typeof DashboardResidentProfileRoute
  '/dashboard/resident/settings': typeof DashboardResidentSettingsRoute
  '/dashboard/security/active-visitors': typeof DashboardSecurityActiveVisitorsRoute
  '/dashboard/security/add-visitor': typeof DashboardSecurityAddVisitorRoute
  '/dashboard/security/visitor-logs': typeof DashboardSecurityVisitorLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/resident'
    | '/dashboard/security'
    | '/dashboard/admin/billing'
    | '/dashboard/admin/complaints'
    | '/dashboard/admin/flats'
    | '/dashboard/admin/maintenance'
    | '/dashboard/admin/notices'
    | '/dashboard/admin/parking'
    | '/dashboard/admin/residents'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/visitors'
    | '/dashboard/resident/billing'
    | '/dashboard/resident/complaints'
    | '/dashboard/resident/flat'
    | '/dashboard/resident/notices'
    | '/dashboard/resident/parking'
    | '/dashboard/resident/profile'
    | '/dashboard/resident/settings'
    | '/dashboard/security/active-visitors'
    | '/dashboard/security/add-visitor'
    | '/dashboard/security/visitor-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardResidentRoute: typeof DashboardResidentRouteWithChildren
  DashboardSecurityRoute: typeof DashboardSecurityRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resident': {
      id: '/dashboard/resident'
      path: '/dashboard/resident'
      fullPath: '/dashboard/resident'
      preLoaderRoute: typeof DashboardResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security/visitor-logs': {
      id: '/dashboard/security/visitor-logs'
      path: '/visitor-logs'
      fullPath: '/dashboard/security/visitor-logs'
      preLoaderRoute: typeof DashboardSecurityVisitorLogsRouteImport
      parentRoute: typeof DashboardSecurityRoute
    }
    '/dashboard/security/add-visitor': {
      id: '/dashboard/security/add-visitor'
      path: '/add-visitor'
      fullPath: '/dashboard/security/add-visitor'
      preLoaderRoute: typeof DashboardSecurityAddVisitorRouteImport
      parentRoute: typeof DashboardSecurityRoute
    }
    '/dashboard/security/active-visitors': {
      id: '/dashboard/security/active-visitors'
      path: '/active-visitors'
      fullPath: '/dashboard/security/active-visitors'
      preLoaderRoute: typeof DashboardSecurityActiveVisitorsRouteImport
      parentRoute: typeof DashboardSecurityRoute
    }
    '/dashboard/resident/settings': {
      id: '/dashboard/resident/settings'
      path: '/settings'
      fullPath: '/dashboard/resident/settings'
      preLoaderRoute: typeof DashboardResidentSettingsRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/profile': {
      id: '/dashboard/resident/profile'
      path: '/profile'
      fullPath: '/dashboard/resident/profile'
      preLoaderRoute: typeof DashboardResidentProfileRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/parking': {
      id: '/dashboard/resident/parking'
      path: '/parking'
      fullPath: '/dashboard/resident/parking'
      preLoaderRoute: typeof DashboardResidentParkingRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/notices': {
      id: '/dashboard/resident/notices'
      path: '/notices'
      fullPath: '/dashboard/resident/notices'
      preLoaderRoute: typeof DashboardResidentNoticesRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/flat': {
      id: '/dashboard/resident/flat'
      path: '/flat'
      fullPath: '/dashboard/resident/flat'
      preLoaderRoute: typeof DashboardResidentFlatRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/complaints': {
      id: '/dashboard/resident/complaints'
      path: '/complaints'
      fullPath: '/dashboard/resident/complaints'
      preLoaderRoute: typeof DashboardResidentComplaintsRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/resident/billing': {
      id: '/dashboard/resident/billing'
      path: '/billing'
      fullPath: '/dashboard/resident/billing'
      preLoaderRoute: typeof DashboardResidentBillingRouteImport
      parentRoute: typeof DashboardResidentRoute
    }
    '/dashboard/admin/visitors': {
      id: '/dashboard/admin/visitors'
      path: '/visitors'
      fullPath: '/dashboard/admin/visitors'
      preLoaderRoute: typeof DashboardAdminVisitorsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/residents': {
      id: '/dashboard/admin/residents'
      path: '/residents'
      fullPath: '/dashboard/admin/residents'
      preLoaderRoute: typeof DashboardAdminResidentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/parking': {
      id: '/dashboard/admin/parking'
      path: '/parking'
      fullPath: '/dashboard/admin/parking'
      preLoaderRoute: typeof DashboardAdminParkingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/notices': {
      id: '/dashboard/admin/notices'
      path: '/notices'
      fullPath: '/dashboard/admin/notices'
      preLoaderRoute: typeof DashboardAdminNoticesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/maintenance': {
      id: '/dashboard/admin/maintenance'
      path: '/maintenance'
      fullPath: '/dashboard/admin/maintenance'
      preLoaderRoute: typeof DashboardAdminMaintenanceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/flats': {
      id: '/dashboard/admin/flats'
      path: '/flats'
      fullPath: '/dashboard/admin/flats'
      preLoaderRoute: typeof DashboardAdminFlatsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/complaints': {
      id: '/dashboard/admin/complaints'
      path: '/complaints'
      fullPath: '/dashboard/admin/complaints'
      preLoaderRoute: typeof DashboardAdminComplaintsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/billing': {
      id: '/dashboard/admin/billing'
      path: '/billing'
      fullPath: '/dashboard/admin/billing'
      preLoaderRoute: typeof DashboardAdminBillingRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminBillingRoute: typeof DashboardAdminBillingRoute
  DashboardAdminComplaintsRoute: typeof DashboardAdminComplaintsRoute
  DashboardAdminFlatsRoute: typeof DashboardAdminFlatsRoute
  DashboardAdminMaintenanceRoute: typeof DashboardAdminMaintenanceRoute
  DashboardAdminNoticesRoute: typeof DashboardAdminNoticesRoute
  DashboardAdminParkingRoute: typeof DashboardAdminParkingRoute
  DashboardAdminResidentsRoute: typeof DashboardAdminResidentsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminVisitorsRoute: typeof DashboardAdminVisitorsRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminBillingRoute: DashboardAdminBillingRoute,
  DashboardAdminComplaintsRoute: DashboardAdminComplaintsRoute,
  DashboardAdminFlatsRoute: DashboardAdminFlatsRoute,
  DashboardAdminMaintenanceRoute: DashboardAdminMaintenanceRoute,
  DashboardAdminNoticesRoute: DashboardAdminNoticesRoute,
  DashboardAdminParkingRoute: DashboardAdminParkingRoute,
  DashboardAdminResidentsRoute: DashboardAdminResidentsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminVisitorsRoute: DashboardAdminVisitorsRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardResidentRouteChildren {
  DashboardResidentBillingRoute: typeof DashboardResidentBillingRoute
  DashboardResidentComplaintsRoute: typeof DashboardResidentComplaintsRoute
  DashboardResidentFlatRoute: typeof DashboardResidentFlatRoute
  DashboardResidentNoticesRoute: typeof DashboardResidentNoticesRoute
  DashboardResidentParkingRoute: typeof DashboardResidentParkingRoute
  DashboardResidentProfileRoute: typeof DashboardResidentProfileRoute
  DashboardResidentSettingsRoute: typeof DashboardResidentSettingsRoute
}

const DashboardResidentRouteChildren: DashboardResidentRouteChildren = {
  DashboardResidentBillingRoute: DashboardResidentBillingRoute,
  DashboardResidentComplaintsRoute: DashboardResidentComplaintsRoute,
  DashboardResidentFlatRoute: DashboardResidentFlatRoute,
  DashboardResidentNoticesRoute: DashboardResidentNoticesRoute,
  DashboardResidentParkingRoute: DashboardResidentParkingRoute,
  DashboardResidentProfileRoute: DashboardResidentProfileRoute,
  DashboardResidentSettingsRoute: DashboardResidentSettingsRoute,
}

const DashboardResidentRouteWithChildren =
  DashboardResidentRoute._addFileChildren(DashboardResidentRouteChildren)

interface DashboardSecurityRouteChildren {
  DashboardSecurityActiveVisitorsRoute: typeof DashboardSecurityActiveVisitorsRoute
  DashboardSecurityAddVisitorRoute: typeof DashboardSecurityAddVisitorRoute
  DashboardSecurityVisitorLogsRoute: typeof DashboardSecurityVisitorLogsRoute
}

const DashboardSecurityRouteChildren: DashboardSecurityRouteChildren = {
  DashboardSecurityActiveVisitorsRoute: DashboardSecurityActiveVisitorsRoute,
  DashboardSecurityAddVisitorRoute: DashboardSecurityAddVisitorRoute,
  DashboardSecurityVisitorLogsRoute: DashboardSecurityVisitorLogsRoute,
}

const DashboardSecurityRouteWithChildren =
  DashboardSecurityRoute._addFileChildren(DashboardSecurityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardResidentRoute: DashboardResidentRouteWithChildren,
  DashboardSecurityRoute: DashboardSecurityRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
